racine:
    path: /
    controller: App\Controller\RacineController:index
test:
    path: /api/cadeaux/test
    controller: App\Controller\HomeController::index
navigation:
    path: /user
    controller: App\Controller\HomeController::index

home:
    path: /user/Acceuil
    controller: App\Controller\HomeController::index

cadeau:
    path: /user/Cadeaux
    controller: App\Controller\HomeController::index

api.cadeau:
    path: /api/cadeaux
    controller: App\Controller\CadeauController::api



admin.cadeau.index:
    path: /admin/cadeau
    controller: App\Controller\Admin\AdminCadeauController::index

admin.cadeau.new:
    path: /admin/cadeau/nouveau
    controller: App\Controller\Admin\AdminCadeauController::nouveau

admin.cadeau.delete:
    path: /admin/cadeau/{id}
    methods: DELETE
    controller: App\Controller\Admin\AdminCadeauController::delete

admin.cadeau.edit:
    path: /admin/cadeau/{id}
    methods: GET|POST
    controller: App\Controller\Admin\AdminCadeauController::edit

login:
    path: /login
    controller: App\Controller\SecurityController::login

logout:
    path: /logout



#invites.index:
#   path: /user/formulaireInvites
#  controller : App\Controller\InviteController::index

#cadeaux.index:
#    path: /user/cadeaux
#    controller: App\Controller\CadeauController::index

#cadeaux.info:
#    path: /user/cadeaux/{slug}-{id}
#    controller: App\Controller\CadeauController::show

#index:
#    path: /
#    controller: App\Controller\DefaultController::index
